allowed-teams:
  - organization-members

triggers:
  /test:
    workflows:
    - test-ping.yaml
    - test-somethings.yaml
    - test-vendor.yaml
    - test-config.yaml
  /ci-ping:
    workflows:
    - test-ping.yaml
  /ci-somethings:
    workflows:
    - test-somethings.yaml 
  /ci-vendor:
    workflows:
    - test-vendor.yaml
  /ci-config:
    workflows:
    - test-config.yaml

workflows:
  test-ping.yaml:
    paths-ignore-regex: (test|Documentation)/
  test-somethings.yaml:
    paths-ignore-regex: (test|Documentation|vendor)/
  test-vendor.yaml:
    paths-regex: vendor/
